import "./utils/global.css"
import {Poppins} from 'next/font/google'

const poppins_init = Poppins({
  subsets:['latin'],
  weight:['100','300','700'],
  variable:'--font-poppins'
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins_init.variable}>{children}</body>
    </html>
  )
}
